# Generated by Django 6.0.3 on 2026-03-23 16:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventario", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="productomodelo",
            name="existencias",
            field=models.PositiveIntegerField(
                default=0, help_text="Cantidad disponible en inventario"
            ),
        ),
    ]
