# Generated by Django 6.0.3 on 2026-03-23 18:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventario", "0002_productomodelo_existencias"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productomodelo",
            name="imagen_url",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
