# Generated by Django 6.0.3 on 2026-03-23 19:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventario", "0003_alter_productomodelo_imagen_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productomodelo",
            name="imagen_url",
        ),
        migrations.AddField(
            model_name="productomodelo",
            name="imagen",
            field=models.ImageField(blank=True, null=True, upload_to="productos/"),
        ),
    ]
