# Generated by Django 6.0.3 on 2026-04-17 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_remove_productomodelo_imagen_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productomodelo',
            name='descuento_porcentaje',
            field=models.PositiveIntegerField(default=0, help_text='Porcentaje de descuento (0 a 100)'),
        ),
        migrations.AddField(
            model_name='productomodelo',
            name='en_oferta',
            field=models.BooleanField(default=False, help_text='Indica si el producto tiene una oferta aplicada'),
        ),
    ]
