# Generated by Django 6.0.3 on 2026-03-16 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tienda', models.CharField(default='LaLico', max_length=200)),
                ('telefono', models.CharField(max_length=20)),
                ('whatsapp', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('direccion', models.TextField()),
                ('horario', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Info de Contacto',
                'verbose_name_plural': 'Info de Contacto',
            },
        ),
        migrations.CreateModel(
            name='MensajeSoporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono_remitente', models.CharField(max_length=20)),
                ('asunto', models.CharField(max_length=255)),
                ('cuerpo', models.TextField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensajes_soporte', to='usuarios.cliente')),
            ],
            options={
                'verbose_name': 'Mensaje de Soporte',
                'verbose_name_plural': 'Mensajes de Soporte',
                'ordering': ['-creado_en'],
            },
        ),
    ]
