# Generated by Django 6.0.3 on 2026-03-16 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soporte', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='infocontacto',
            options={'verbose_name': 'Info de Contacto y Redes', 'verbose_name_plural': 'Info de Contacto y Redes'},
        ),
        migrations.RemoveField(
            model_name='infocontacto',
            name='whatsapp',
        ),
        migrations.AddField(
            model_name='infocontacto',
            name='facebook_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='infocontacto',
            name='instagram_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='infocontacto',
            name='whatsapp_link',
            field=models.URLField(blank=True, help_text='Link directo al chat de WhatsApp', null=True),
        ),
        migrations.CreateModel(
            name='SoportePago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono_remitente', models.CharField(max_length=20)),
                ('comprobante_url', models.URLField(help_text='URL de la imagen del comprobante en Supabase', max_length=500)),
                ('notas', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='soportes_pago', to='usuarios.cliente')),
            ],
            options={
                'verbose_name': 'Soporte de Pago',
                'verbose_name_plural': 'Soportes de Pago',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.DeleteModel(
            name='MensajeSoporte',
        ),
    ]
