FROM python:3.12-slim

WORKDIR /app

# Dependencias mínimas
RUN apt-get update && apt-get install -y --no-install-recommends gcc libpq-dev && rm -rf /var/lib/apt/lists/*

COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt gunicorn

COPY . /app/

RUN python manage.py collectstatic --noinput
RUN python manage.py migrate # Realizar las migraciones
RUN python manage.py crear_admin --username admin --password ${DJANGO_ADMIN_PASSWORD}

EXPOSE 8000
