# Generated by Django 6.0.3 on 2026-05-08 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('granizados', '0001_initial'),
        ('inventario', '0005_productomodelo_descuento_porcentaje_and_more'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempedido',
            name='granizado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='granizados.granizado'),
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.productomodelo'),
        ),
    ]
