# Generated by Django 6.0.3 on 2026-05-14 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_itempedido_granizado_alter_itempedido_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='domicilio',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='direccion',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE_PAGO', 'Pendiente de Pago'), ('PAGO_SUBIDO', 'Pago Subido'), ('PAGO_VERIFICADO', 'Pago Verificado'), ('PAGO_RECHAZADO', 'Pago Rechazado'), ('PREPARANDO', 'Preparando'), ('DESPACHADO', 'Despachado'), ('ENTREGADO', 'Entregado')], default='PENDIENTE_PAGO', max_length=20),
        ),
    ]
