# Generated by Django 6.0.3 on 2026-05-08 23:11

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('categoria', models.CharField(choices=[('fruta', 'Fruta'), ('licor', 'Licor'), ('complemento', 'Complemento')], max_length=20)),
                ('precio_adicional', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('disponible', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ingrediente',
                'verbose_name_plural': 'Ingredientes',
                'ordering': ['categoria', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Granizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiene_alcohol', models.BooleanField(default=False)),
                ('precio_base', models.DecimalField(decimal_places=2, default=Decimal('12000.00'), max_digits=10)),
                ('precio_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('ingredientes', models.ManyToManyField(related_name='granizados', to='granizados.ingrediente')),
            ],
            options={
                'verbose_name': 'Granizado',
                'verbose_name_plural': 'Granizados',
                'ordering': ['-creado_en'],
            },
        ),
    ]
