# Generated by Django 6.0.3 on 2026-03-23 16:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("soporte", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="soportepago",
            name="imagen_url",
        ),
        migrations.AddField(
            model_name="soportepago",
            name="comprobante",
            field=models.ImageField(blank=True, null=True, upload_to="comprobantes/"),
        ),
    ]
