# Generated by Django 4.2.28 on 2026-03-17 20:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarritoCompraModelo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_publico', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('estado', models.CharField(choices=[('abierto', 'abierto'), ('convertido', 'convertido')], default='abierto', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Carrito de Compra',
                'verbose_name_plural': 'Carritos de Compra',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='PedidoModelo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_publico', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('cliente_telefono', models.CharField(max_length=20)),
                ('nombre_cliente', models.CharField(max_length=200)),
                ('direccion_entrega', models.TextField()),
                ('observaciones_entrega', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('pendiente_comprobante', 'pendiente_comprobante'), ('en_revision', 'en_revision'), ('aprobado', 'aprobado'), ('rechazado', 'rechazado'), ('vencido', 'vencido')], default='pendiente_comprobante', max_length=30)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('reservado_hasta', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='ItemPedidoModelo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto_id', models.PositiveBigIntegerField()),
                ('nombre_producto', models.CharField(max_length=255)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cantidad', models.PositiveIntegerField()),
                ('subtotal_linea', models.DecimalField(decimal_places=2, max_digits=12)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ventas.pedidomodelo')),
            ],
            options={
                'verbose_name': 'Item de Pedido',
                'verbose_name_plural': 'Items de Pedido',
            },
        ),
        migrations.CreateModel(
            name='ComprobantePagoModelo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruta_archivo', models.CharField(max_length=500)),
                ('notas_cliente', models.TextField(blank=True)),
                ('motivo_rechazo', models.TextField(blank=True)),
                ('estado_validacion', models.CharField(choices=[('pendiente', 'pendiente'), ('aprobado', 'aprobado'), ('rechazado', 'rechazado')], default='pendiente', max_length=20)),
                ('subido_en', models.DateTimeField(blank=True, null=True)),
                ('validado_en', models.DateTimeField(blank=True, null=True)),
                ('administrador_validador_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comprobante', to='ventas.pedidomodelo')),
            ],
            options={
                'verbose_name': 'Comprobante de Pago',
                'verbose_name_plural': 'Comprobantes de Pago',
            },
        ),
        migrations.CreateModel(
            name='ItemCarritoModelo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto_id', models.PositiveBigIntegerField()),
                ('cantidad', models.PositiveIntegerField()),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ventas.carritocompramodelo')),
            ],
            options={
                'verbose_name': 'Item de Carrito',
                'verbose_name_plural': 'Items de Carrito',
                'unique_together': {('carrito', 'producto_id')},
            },
        ),
    ]
